### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by benrozsa** [robence/nest-cra-starter#5]
- [x] Typescript
 - [x] Dev Mode (Live Reload)
 - [x] Precommit - Husky
    - [x] Lint only staged files - lint-staged
    - [x] ESLint & Prettier check
    - [x] Typescript compiles
 - [x] CircleCI
    - [x] yarn.lock cached
    - [x] run yarn test command
    - [x] send email on failure
